### ISSUE TITLE
Create debian package

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/eccodes-simc#11]

**Comment by dcesari** [comment]
Here all the job is made in the spec, so it has to be rethought.

**Comment by spanezz** [comment]
The package builds on bullseye and jammy.

I ported the definitions generation to python, and added patch autodetection

**Comment by edigiacomo** [comment]
I moved the debian dir to ubuntu/jammy, debian/bullseye and debian/sid branches in order to build the package with git-buildpackage.

**Comment by spanezz** [comment]
Looks fine, and it built fine
